### ISSUE TITLE
Can't seem to change any of the variables.

### ISSUE THREAD

**Issue by berendsliedrecht** [zalog/placeholder-loading#14]
Using Angular 9.

Followed the steps: 

1. npm install...
2. import the node module
3. Add the variables in styles.scss
4. Tries to change the variable values, #fff to #123

Background did not change from white.

Any idea on what I did wrong? Thanks!

**Comment by zalog** [comment]
Hi B,

Please check the import order.
And also, please check [how `!default` works in sass](https://sass-lang.com/documentation/variables#default-values).

**Comment by zalog** [comment]
@blu3beri, all good? Can we close this?

**Comment by zalog** [comment]
We'll close this. Thanks @blu3beri for using the package and taking time to open this :)
