### ISSUE TITLE
No animation without .ph-item

### ISSUE THREAD

**Issue by MickL** [zalog/placeholder-loading#20]
I would like to place just the elements (image placeholder, text placeholder) without the frame created by `.ph-item`. But if I do so no animation is running.

My suggestion would be:

- Let everything work without the wrapper `.ph-item`, OR
- Create a second class `.ph-item-no-border` or an additonal class `.clean` that removes border, margin and padding

I would prefer the first option so it is easy to place an image-placeholder for example without the need of a wrapper ph-item. On the other hand having a wrapper would allow for having centered content as described in #21 

In addition the values of .ph-item (border, padding, margin) should be configurable through variables imo.

**Comment by MickL** [comment]
I made a PR where I added a `.clean` class along with some other small improvements.

**Comment by zalog** [comment]
Great @MickL! Thanks for your time!
I like the issues that you came up with.
I'll get back to this as soon as possible.

**Comment by MickL** [comment]
@zalog Could you check my PR yet? :)

**Comment by zalog** [comment]
Not yet, sorry :(
But I hope soon :)
