### ISSUE TITLE
doesn't work with ionic

### ISSUE THREAD

**Issue by stewones** [zalog/placeholder-loading#3]
can you check for that?

**Comment by zalog** [comment]
Sure! I can try.
Can you cook your code in a [fiddle](https://jsfiddle.net/)/[pen](https://codepen.io/)/[stackblitz](https://stackblitz.com/) like?

**Comment by stewones** [comment]
Sorry, I was not clear. the problem happens when running on device, the animation effect doesn't work, I'll cook it for you as soon as I can

**Comment by zalog** [comment]
Hey @stewwan, any news?

**Comment by stewones** [comment]
lol it seemed to be a side effect. def not a problem with your lib, thanks.

**Comment by zalog** [comment]
Ah, ok. Thanks!
Happy coding :D
