### ISSUE TITLE
Sass Deprecation Warning

### ISSUE THREAD

**Issue by bay-jacewhitten** [zalog/placeholder-loading#37]
DEPRECATION WARNING: Using / for division is deprecated and will be removed in Dart Sass 2.0.0.

Recommend to run the migration command and commit. I can do the PR if you like.

Thanks!

**Comment by zalog** [comment]
Thanks for your feedback. There is already a local branch with some updates. I'll keep you posted if we don't fix this there :)

**Comment by slobo** [comment]
Thanks for the great work on this component. Is there an ETA on new release that would solve the deprecation warning?

Thanks!

**Comment by zalog** [comment]
Oh... thanks for this kind reminder. I think somewhere this week. Sorry for the delay :)

**Comment by zalog** [comment]
~Do we still have this problem? I can't replicate it :(~

L.E. Found it! It's a wip :)

**Comment by zalog** [comment]
Done :)
